name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: lengolf-forms
  REGION: asia-southeast1
  SERVICE_NAME: lengolf-bot
  REPOSITORY: line-bot-containers
  REGISTRY: asia-southeast1-docker.pkg.dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm ci

    - name: Setup GCloud Auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        project_id: lengolf-forms

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker for Artifact Registry
      run: |-
        gcloud auth configure-docker $REGISTRY --quiet

    - name: Build and Push Container
      run: |-
        echo "Building image for project: $PROJECT_ID"
        docker build -t $REGISTRY/$PROJECT_ID/$REPOSITORY/$SERVICE_NAME:${{ github.sha }} .
        docker push $REGISTRY/$PROJECT_ID/$REPOSITORY/$SERVICE_NAME:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |-
        # Create or update the secret for Google Calendar credentials
        echo '${{ secrets.GOOGLE_CALENDAR_SA_KEY }}' > calendar-sa.json
        gcloud secrets create calendar-service-account --data-file=calendar-sa.json --replication-policy="automatic" || true
        gcloud secrets versions add calendar-service-account --data-file=calendar-sa.json
        rm calendar-sa.json

        # Deploy the service
        gcloud run deploy $SERVICE_NAME \
          --image $REGISTRY/$PROJECT_ID/$REPOSITORY/$SERVICE_NAME:${{ github.sha }} \
          --platform managed \
          --region $REGION \
          --allow-unauthenticated \
          --set-env-vars="LINE_ACCESS_TOKEN=${{ secrets.LINE_ACCESS_TOKEN }}" \
          --set-env-vars="SUPABASE_URL=${{ secrets.SUPABASE_URL }}" \
          --set-env-vars="SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" \
          --set-env-vars="CALENDAR_BAY1=${{ secrets.CALENDAR_BAY1 }}" \
          --set-env-vars="CALENDAR_BAY2=${{ secrets.CALENDAR_BAY2 }}" \
          --set-env-vars="CALENDAR_BAY3=${{ secrets.CALENDAR_BAY3 }}" \
          --set-env-vars="NODE_ENV=production" \
          --update-secrets="/secrets/service-account.json=calendar-service-account:latest" \
          --port=8080