name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: asia-southeast1
  SERVICE_NAME: lengolf-bot

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm ci

    - name: Setup GCloud Auth
      id: auth
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build and Push Container
      run: |-
        docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ github.sha }} .
        docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |-
        # First create a secret for Google Calendar credentials
        echo '${{ secrets.GOOGLE_CALENDAR_SA_KEY }}' > calendar-sa.json
        gcloud secrets create calendar-service-account --data-file=calendar-sa.json --replication-policy="automatic" || true
        gcloud secrets versions add calendar-service-account --data-file=calendar-sa.json
        rm calendar-sa.json

        # Deploy the service
        gcloud run deploy $SERVICE_NAME \
          --image gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ github.sha }} \
          --platform managed \
          --region $REGION \
          --allow-unauthenticated \
          --set-env-vars="LINE_ACCESS_TOKEN=${{ secrets.LINE_ACCESS_TOKEN }}" \
          --set-env-vars="SUPABASE_URL=${{ secrets.SUPABASE_URL }}" \
          --set-env-vars="SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" \
          --set-env-vars="CALENDAR_BAY1=${{ secrets.CALENDAR_BAY1 }}" \
          --set-env-vars="CALENDAR_BAY2=${{ secrets.CALENDAR_BAY2 }}" \
          --set-env-vars="CALENDAR_BAY3=${{ secrets.CALENDAR_BAY3 }}" \
          --set-env-vars="NODE_ENV=production" \
          --update-secrets="/secrets/service-account.json=calendar-service-account:latest" \
          --port=8080